site_name: SyncLionPaw Blog
site_url: "https://SyncLionPaw.github.io"  # GitHub Pages 的部署地址
site_author: "SyncLionPaw"  # 作者名称
repo_url: "https://github.com/SyncLionPaw/SyncLionPaw.github.io"  # 仓库地址
repo_name: "SyncLionPaw"  # 右上角显示的仓库名称

theme:
  name: material
  language: zh
  features:
    - header.autohide # 自适应隐藏header
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono


nav:
  - Home: index.md
  - 'Golang':
    - 在函数内定义函数: 'golang/func/innerfunc.md'
    - io.Reader: 'golang/ioreader/ioreader.md'
    - bufio: 'golang/ioreader/bufio.md'
    - embed: 'golang/embed/embed.md'
  - 'python':
    - 默认字典: 'python/collections/defaultdict_use.md'
  - 'algorithm':
    - 会议室2: 'algo/greedy/会议室2.md'
    - 编辑距离: 'algo/dp/编辑距离.md'
  - 'mysql':
    - 数据行: 'mysql/data.md'
  - 'redis':
    - 当缓存: 'redis/as_cache/cache_q.md'

plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags

markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/SyncLionPaw"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/kaggle"
  generator: false  # 隐藏页脚的 "使用 MkDocs 材料制造" 文字